//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace freelance.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderBoard
    {
        public int OrderBoardID { get; set; }
        public int EmployerID { get; set; }
        public int UserID { get; set; }
        public int RoleID { get; set; }
    
        public virtual Employer Employer { get; set; }
        public virtual Role Role { get; set; }
        public virtual User User { get; set; }
    }
}
